### ISSUE TITLE
Is this package currently working?

### ISSUE THREAD

**Issue by choijeehyuk** [iyarsius/stockx-scraper#12]
First of all, thank you for making the package.
I used this package, but I got 400 errors in the search function of StockxClient class.
After comparing the stockx api request with the package code, there was a slight difference in the graphql code, so I corrected it, but the result remains the same.
I put proxy as a factor, but I didn't put cookie, but is this a problem? Thank you.
<img width="651" alt="스크린샷 2023-03-14 오후 6 21 27" src="https://user-images.githubusercontent.com/85402926/224954919-d828a094-9f40-4fd9-86cd-3cf511bd9474.png">

this is my code! 

{
    "error": {
        "message": "Request failed with status code 400",
        "name": "AxiosError",
        "stack": "AxiosError: Request failed with status code 400\n    at settle (/Users/choijihyuk/Desktop/company/snippo_kream/node_modules/axios/dist/node/axios.cjs:1901:12)\n    at IncomingMessage.handleStreamEnd (/Users/choijihyuk/Desktop/company/snippo_kream/node_modules/axios/dist/node/axios.cjs:2953:11)\n    at IncomingMessage.emit (node:events:525:35)\n    at endReadableNT (node:internal/streams/readable:1358:12)\n    at processTicksAndRejections (node:internal/process/task_queues:83:21)",
        "config": {
            "transitional": {
                "silentJSONParsing": true,
                "forcedJSONParsing": true,
                "clarifyTimeoutError": false
            },
            "adapter": [
                "xhr",
                "http"
            ],
            "transformRequest": [
                null
            ],
            "transformResponse": [
                null
            ],
            "timeout": 0,
            "xsrfCookieName": "XSRF-TOKEN",
            "xsrfHeaderName": "X-XSRF-TOKEN",
            "maxContentLength": -1,
            "maxBodyLength": -1,
            "env": {
                "Blob": null
            },
            "headers": {
                "Accept": "application/json",
                "Content-Type": "application/json",
                "user-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.2 Safari/605.1.15",
                "cookie": "stockx_homepage=sneakers; language_code=en-us; stockx_selected_region=US; stockx_preferred_market_activity=sales; stockx_dismiss_modal=true; IR_gbd=stockx.com; cookie_policy_accepted=true; stockx_product_visits=4; stockx_default_sneakers_size=All; OptanonConsent=isGpcEnabled=1&datestamp=Tue%2BMar%2B14%2B2023%2B18%253PM19%253PM50%2B%2B09%3A00&version=6.36.0&isIABGlobal=false&hosts=&consentId=124f4404-36c7-437d-aeee-1b67d82251ee&interactionCount=1&landingPath=NotLandingPage&groups=C0001%253A1%252CC0002%253A1%252CC0005%253A1%252CC0004%253A1%252CC0003%253A1; ",
                "apollographql-client-version": "2023.02.26.03",
                "apollographql-client-name": "Iron",
                "app-platform": "Iron",
                "app-version": "2023.02.26.03",
                "accept-language": "en-US",
                "x-stockx-device-id": "x",
                "Content-Length": "1557",
                "Accept-Encoding": "gzip, compress, deflate, br"
            },
            "method": "post",
            "url": "https://stockx.com/api/p/e",
            "data": "{\"operationName\":\"GetSearchResults\",\"query\":\"query GetSearchResults($filtersVersion: Int, $query: String!, $page: BrowsePageInput, $sort: BrowseSortInput, $staticRanking: BrowseExperimentStaticRankingInput) {\\n      browse(\\n        query: $query\\n        page: $page\\n        sort: $sort\\n        filtersVersion: $filtersVersion\\n        experiments: {staticRanking: $staticRanking}\\n      ) {\\n        categories {\\n          id\\n          name\\n          count\\n    }\\n    results {\\n          edges {\\n            objectId\\n            node {\\n              ... on Product {\\n                id\\n                urlKey\\n                primaryTitle\\n                secondaryTitle\\n                media {\\n                  thumbUrl\\n            }\\n            brand\\n            productCategory\\n          }\\n          ... on Variant {\\n                id\\n                product {\\n                  id\\n                  urlKey\\n                  primaryTitle\\n                  secondaryTitle\\n                  media {\\n                    thumbUrl\\n              }\\n              brand\\n              productCategory\\n            }\\n          }\\n        }\\n      }\\n      pageInfo {\\n            limit\\n            page\\n            pageCount\\n            queryId\\n            queryIndex\\n            total\\n      }\\n    }\\n    sort {\\n          id\\n          order\\n    }\\n  }\\n}\\n\",\"variables\":{\"filtersVersion\":4,\"query\":\"jordan 123123\",\"sort\":{\"id\":\"featured\",\"order\":\"DESC\"},\"page\":{\"index\":1,\"limit\":10},\"staticRanking\":{\"enabled\":false}}}",
            "httpsAgent": {
                "_events": {},
                "_eventsCount": 0,
                "timeout": null,
                "maxFreeSockets": 1,
                "maxSockets": 1,
                "maxTotalSockets": null,
                "sockets": {},
                "freeSockets": {},
                "requests": {},
                "options": {},
                "secureProxy": false,
                "proxy": {
                    "host": "103.156.141.100",
                    "port": 80
                }
            }
        },
        "code": "ERR_BAD_REQUEST",
        "status": 400
    }
}

this is my error message!

**Comment by iyarsius** [comment]
Hi, the query was not encoded as URI component so it was not 100% accurate, i fixed it and should work better for you now

**Comment by choijeehyuk** [comment]
Thank you for updating it! I just ran this package v2.2.2 and got the same result. Does it work on your computer??
when use search function, the transmission data includes escape characters. Is there no problem with this?

"data": "{\"operationName\":\"GetSearchResults\",\"query\":\"query GetSearchResults($filtersVersion: Int, $query: String!, $page: BrowsePageInput, $sort: BrowseSortInput, $staticRanking: BrowseExperimentStaticRankingInput) {\\n      browse(\\n        query: $query\\n        page: $page\\n        sort: $sort\\n        filtersVersion: $filtersVersion\\n        experiments: {staticRanking: $staticRanking}\\n      ) {\\n        categories {\\n          id\\n          name\\n          count\\n    }\\n    results {\\n          edges {\\n            objectId\\n            node {\\n              ... on Product {\\n                id\\n                styleId\\n                description\\n                urlKey\\n                traits {\\n                    name\\n                    value\\n                  }\\n                primaryTitle\\n                secondaryTitle\\n                media {\\n                  thumbUrl\\n            }\\n            brand\\n            productCategory\\n          }\\n          ... on Variant {\\n                id\\n                product {\\n                  id\\n                  urlKey\\n                  primaryTitle\\n                  secondaryTitle\\n                  media {\\n                    thumbUrl\\n              }\\n              brand\\n              productCategory\\n            }\\n          }\\n        }\\n      }\\n      pageInfo {\\n            limit\\n            page\\n            pageCount\\n            queryId\\n            queryIndex\\n            total\\n      }\\n    }\\n    sort {\\n          id\\n          order\\n    }\\n  }\\n}\\n\",\"variables\":{\"filtersVersion\":4,\"query\":\"yeezy\",\"sort\":{\"id\":\"featured\",\"order\":\"DESC\"},\"page\":{\"index\":1,\"limit\":10},\"staticRanking\":{\"enabled\":false}}}",

The escape text was only visible to Postman...

**Comment by iyarsius** [comment]
Are you sure it's still a 400 error ? Not a 403 ?

**Comment by choijeehyuk** [comment]
Yes, 400 error.

**Comment by iyarsius** [comment]
Can you send me more informations about your code ? Its working fine on my side

**Comment by choijeehyuk** [comment]
const client = new StockxClient({
      proxys: ["http://103.156.141.100:80"],
    });

    const products = await client.search({ query: "yeezy" });  <----- error function
    const firstResult = products[0];

    // fetch variants and some data
    await firstResult.fetch();

    // get related products
    const related = await firstResult.getRelatedProducts();
    console.log(related);

    // related works like normal products
    const result = await related.fetch();
    console.log(result);

**Comment by iyarsius** [comment]
I tried with your exact code, it seems to be a proxy issue, try without proxy or change it and it should work.

**Comment by choijeehyuk** [comment]
Thank you! It's working fine now.
