### ISSUE TITLE
configRequest.fetchRelatedProducts is not a function at Object.getProductGroup

### ISSUE THREAD

**Issue by riccardoLSV** [iyarsius/stockx-scraper#2]
i get this error when using getProductGroup() 
TypeError: configRequest.fetchRelatedProducts is not a function at Object.getProductGroup (index.js?8945:153:1)

looking in the configRequest.js file seems that fetchRelatedProducts function doesn't exist

**Comment by iyarsius** [comment]
This issue has been resolved, it was caused when I switched to graphQl api instead of algolia. Thanks for your report
