### ISSUE TITLE
Error 407 when I use proxy

### ISSUE THREAD

**Issue by LyesEpitech** [iyarsius/stockx-scraper#4]
Hello,

Thanks for this repo !

When I try to use proxy it's dont working. 

I use oxylabs proxy. They work weel in other cases.

I have this error:
![image](https://user-images.githubusercontent.com/71270084/162252091-f38029bc-8207-495f-8509-60c2665996f0.png)

**Comment by iyarsius** [comment]
Hi, did you used user:pass@ip:port format ?

**Comment by LyesIsogeo** [comment]
Oh my bad ! I use my proxy with their current format: ip:port:user:password. 

Thanks you !
