### ISSUE TITLE
I get 404 all the time

### ISSUE THREAD

**Issue by MiftahMohammed** [iyarsius/stockx-scraper#5]
Hello,
first of all thanks for sharing this!

Can you still get access to stockX through the api ? i got 404 al the time :(, any idea ?

**Comment by iyarsius** [comment]
Hi,

It's all working in my side. It's a littles bit difficult to fix your error without your code

**Comment by MiftahMohammed** [comment]
it worked now ! thanks for your quick reply. I tried my mobile connection and it's working, seems my residential ip address is flagged XD

**Comment by iyarsius** [comment]
Weird, when IP are flagged you should receive 403 error, if you get this error again please report the bug here
