### ISSUE TITLE
How to pass cookies?

### ISSUE THREAD

**Issue by Kanekixxx** [iyarsius/stockx-scraper#7]
Hi, i'm having some trouble passing the cookies for the scraper.
I need to pass in the format string "name=value;name2=value2"?
I have this object of cookies :
![image](https://user-images.githubusercontent.com/89610361/176157489-c69a0c7e-c680-4484-bfc5-755fdd93edb4.png)

**Comment by iyarsius** [comment]
Hi, yeah juste pass it as string format "Key=value;"

**Comment by Kanekixxx** [comment]
![image](https://user-images.githubusercontent.com/89610361/176184246-b1182346-939d-4f17-855f-fc844270af4f.png)
![image](https://user-images.githubusercontent.com/89610361/176184299-23108da1-ac4a-4a36-bedb-12f0667122e5.png)
![image](https://user-images.githubusercontent.com/89610361/176184340-e103e78a-f210-4896-a10f-56828a44bea1.png)

What's wrong?

**Comment by iyarsius** [comment]
Make sure you use the last version of this module.

`npm i stockx-scraper@1.6.9`

**Comment by Kanekixxx** [comment]
Yeah I already check it, and tried passing different cookie like only _px3 and _pxvid but it keeps me getting 403 error even with mobile connection.

**Comment by Kanekixxx** [comment]
![image](https://user-images.githubusercontent.com/89610361/176190044-f331c226-6d21-4c5b-b775-02daf143d22b.png)
The version, the cookie and the ip it's good, i don't know what's the error can be

**Comment by iyarsius** [comment]
If you are getting 403, your cookies are probably not good.

Px cookies is generated from perimeterX security loader (A script that creates a fingerprint of your browser), It is linked to a probability score whether you are a bot or not. If you import flagged cookies you will Always get 403 errors.

3 ways to solve this issue:

1. Create a script able to solve the security loader with a sufficient score.
2. Using a better px cookie provider.
3. Use browser to farm and import them in the scraper.

**Comment by Kanekixxx** [comment]
I'm importing it from the browser using puppeteer stealth without need to solve challenge, i tried to import mine from the browser and didn't work

**Comment by iyarsius** [comment]
it seems to be a new protection, i'll investigate on it and update this repo as soon as possible.

**Comment by Kanekixxx** [comment]
Thank you very much! I'll wait for the new release

**Comment by iyarsius** [comment]
everything should work now
