### ISSUE TITLE
Errors on launch

### ISSUE THREAD

**Issue by springerjanek** [iyarsius/stockx-scraper#8]
![image](https://user-images.githubusercontent.com/54078220/196504440-63881a83-9d56-44e4-a242-fdad3fa4fdca.png)
![image](https://user-images.githubusercontent.com/54078220/196504596-3ff0f352-8ba6-4b16-9af7-cec20439154a.png)

Cant get to work properly. When i launch my app this errors im getting.

**Comment by iyarsius** [comment]
Run it on server side using node.js
